### ISSUE TITLE
New update from Discord messed up the theme. This is what it looks like (I'm still using Dark Theme, even though it looks like I'm using Light.)

### ISSUE THREAD

**Issue by DavidScann** [PlusInsta/discord-plus#21]
![image](https://user-images.githubusercontent.com/53106687/64570527-13589c80-d38b-11e9-932e-00ffa64493e5.png)
Font seems to be broken, scaling of the texts seems a bit off, the Discord+ logo's missing, most obvious are the channels seem to be at a lighter, default Discord's color.

**Comment by PlusInsta** [comment]
The issue was caused by Discord changing the way the app is themed. Bad news, you'll have to update. Good news, it'll be significantly easier to maintain the theme moving forward because of the new variables Discord uses.

[Grab the latest release from here](https://github.com/PlusInsta/discord-plus/releases/latest), and you're good to go.
