### ISSUE TITLE
Scroll bar locks up click behavior in friend list

### ISSUE THREAD

**Issue by Glamurio** [PlusInsta/discord-plus#50]
When scrolling down, the scroll bar gets stuck. This is visually indicated by the scrollbar jittering rapidly up and down. The result of this means that you can no longer click the friend list until you scroll an additional time or somehow free the scrollbar from this state.

1. Access friend list
2. Scroll down (2 scrolls, vertical scroll lines 8)
3. Attempt to click on any entry in the friend list

Unfortunately I cannot screenshot the error because, as I mentioned, the visual indication is jittering and it is click behavior that gets disabled. My assumption is that this is caused by a faulty scroll height calculation. 

It happens after 2 scrolls when the mouse wheel vertical scroll is set to 8 number of lines on a 1920x1080 monitor. I can confirm this because it happens after 5 scrolls when the vertical scroll is set to 7.

It's most definitely related to the theme, as it only occurs when using the theme. Which is a shame, because this is my favorite theme.

**Comment by PlusInsta** [comment]
Can't reproduce. I haven't messed with the scrollbar behavior in the friends list (in fact, the friends list is almost completely vanilla outside of basic styling). I don't "calculate scroll heights" because I have literally no reason to.

I'd suggest you check your plugin list for anything that's altering friends list behavior. You're free to upload a video of this behavior (preferably with a program that shows your mouse + clicking), it may help narrow down the issue.
