### ISSUE TITLE
Backgrounds not dark enough

### ISSUE THREAD

**Issue by leeroiyy** [PlusInsta/discord-plus#9]
i live the theme only got one problem with it how can i fix the blackness 
![discord_2019-01-21_14-28-02](https://user-images.githubusercontent.com/46880854/51452992-c9359300-1d88-11e9-9c71-3949b92d123c.jpg)

**Comment by PlusInsta** [comment]
Judging by that screenshot alone, it seems the theme is working as intended. The wallpaper you're using is pretty light, though, so you might want to manually adjust the `transparency` values so the text is more legible since the theme was made with darker backgrounds in mind.

To do this, add the following lines to the `:root` of the theme (assuming you're using the Master Edition):
```
	--transparency: rgba(0,0,0,0.6);
	--transparency-dark: rgba(0,0,0,0.7);
	--transparency-darker: rgba(0,0,0,0.8);
```
Then change it to something like:

```
	--transparency: rgba(0,0,0,0.7);
	--transparency-dark: rgba(0,0,0,0.8);
	--transparency-darker: rgba(0,0,0,0.9);
```

It should look something like this (except, with your own values):
![Screenshot of Atom showing the modified root variables](https://user-images.githubusercontent.com/38794586/52618416-0defae00-2e9f-11e9-9a50-2d7f2ddba08b.png)


Please experiment with the alpha value (the rightmost decimal) until you get a desirable result. You can use double decimals (.75, etc) too, if you need to. Thanks for asking!
